Add Support for mTLS Authentication
streamnative/terraform-provider-pulsar pull request #73
Opened 2023-01-23 15:41 UTC by oliverisaac

### Motivation

Add support for mTLS Auth as that is what we are using for authentication with pulsar.

### Modifications

- Added the `tls_cert_file_path` and `tls_key_file_path` option. 

- A tiny bit of cleanup on the readme

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is already covered by the existing provider tests

### Documentation

- [x] `doc-required`  
- [ ] `no-need-doc`  
- [x] `doc`

2023-01-23 15:49 UTC, LanceSandino commented
Thanks, my company really needs this! 👍🏽

2023-02-07 18:30 UTC, oliverisaac commented
@maxsxu , can I get a review on this please?

2023-02-08 03:53 UTC, nodece commented on pulsar/provider.go
> +				DefaultFunc: schema.MultiEnvDefaultFunc([]string{"PULSAR_TLS_CERT_FILE", "PULSAR_TLS_CERT_FILE_PATH"}, ""),
```suggestion
				DefaultFunc: schema.MultiEnvDefaultFunc([]string{"PULSAR_TLS_CERT_FILE_PATH"}, ""),
```

2023-02-08 03:53 UTC, nodece commented on pulsar/provider.go
> +				DefaultFunc: schema.MultiEnvDefaultFunc([]string{"PULSAR_TLS_KEY_FILE", "PULSAR_TLS_KEY_FILE_PATH"}, ""),
```suggestion
				DefaultFunc: schema.MultiEnvDefaultFunc([]string{"PULSAR_TLS_KEY_FILE_PATH"}, ""),
```

2023-02-08 03:55 UTC, nodece requested changes
Good work!

2023-02-08 03:55 UTC, nodece commented
Could you remove `.DS_Store` file?

2023-02-09 15:34 UTC, oliverisaac commented
Thanks @nodece! Got those changes dropped in.

2023-02-22 14:30 UTC, maxsxu approved these changes
@oliverisaac LGTM. Thanks for your contributions!

2023-02-22 14:43 UTC, maxsxu approved these changes

2023-02-22 14:46 UTC, merged